language: java
script: gradle dist -x test
sudo: false
install:
- echo sonatypeUsername=none >> gradle.properties
- echo sonatypePassword=none >> gradle.properties

deploy:
  provider: releases
  api_key:
    secure: z6/aMmzGCJvZoCrYSaRotZx9ZydCkySB0hVohhquoJuO/z6bMXmjATxORnjiTgCO04gHl6QUWt+mBmJ1vlcD7ddOg9GHIavbGktAZce4XVZLqm6/rgVLPfIqiCc6atEiw8gTe6Hi2btNew4wPITX0tm0GC43JGUI99wOYyp4sXIf8tX04wyU1SFTR0+1Cek2CruesWESI/NmenShQIeXCHpqYXddLJC+M6lA14X/egny53zarJKlFXRrMi70vdj5B5S0r5TB55W/Ue00rjUc+V5pl8SN/P5zUF9rEBUCcp7ZLDwaATM761fdKGVLDZzok1j2ZkYaTBA2r8Y3Zmrp2p9RvgiVIMS+Zn7k8U4PN1oXwbpO629vm7ZC6jOHtY8Vy5vLRJVvLMWDgcplOlZLA/jICQZE41oyERabTE+ba2J0mQZuTu05s+vQ7H/spdB4JJsK4WxMW2E4T06Z5PNN1th4JX24i81Y7Er4diVM57uGmb6lGNjqcl2vIyIwY8W5svs1KJAKVDM3LSEzr4Y96e8jIw/o13PTnkikpLwbooCOGS0NhPo+eoe7y+BZ8EAlJjRrCsxuWzo5trebZyKCxv2FUMXuiQmgEXYIzNFT8fLakCASrAVOwOKN9am83kpERA/q0RVA7OBTZCOEzzR/K4N8IKa5ZJpbqSZV5NsJBDw=
  file:
    - build/distributions/xmlcalabash1-gradle-$TRAVIS_TAG.zip
  on:
    all_branches: true
    tags: true

