language: java
script: ./gradlew dist -x test
sudo: false
install:
- echo sonatypeUsername=none >> gradle.properties
- echo sonatypePassword=none >> gradle.properties
deploy:
  provider: releases
  api_key:
    secure: no4UA/ykHmXH0MNOMXmFeSWL2RHM8YDS8M59tiYpe8EgyYOkEGfI2Z9xz3lhQLDIYo87XmHm4KD6Kg5JuVpmfBgnHy2d5RtJ08TZ3bhgjV+EbLHeCrry7BVRDPVhD3b/ttfbocw/2BWsAMbDbyOiXwjwYT4Nj7ctDURI+N1joJ16PdACb9RuzZvi0DKRkKV5Prqo7PUDivJYsn3Qjv0YQJzW6kaVautWjfv/ei8szMIaT2kBKKghY87SRoHAIAqDtXiGB/gxjtm+usXMWeo3HGDs6sXEZDlIccBAZcC3JqzstDdaEEaXISit8VA30aQD/FzK+WB+bBf01Ri67R+tFJ4xKRzLQZKXGgA+LAUmv1hmnLXxnd2vMhPJTtxdf+aaAlYD1D4N6zJbxyTsW0vTm5zAHybrZUQ6kABlRYIjKnmbdVdhl26PnBRQDPIAPLcfKYBi5K8OPGb3LCpnUepTwEqKoJ1PU3QsG0a2ZXt4foxl23HeXR1IlLHlvRJQpFUXejl/PWhJyNsnOmev5jaUMAu/9+ma+fnOemRyloS5QMDxm/x7CVsnnsfkOV9sjCKG6DWXP/3tJK33E4ezmC59bkrDYWk40wYCnO7bHAHhg02pAHqbIoiyabG9rZrJgLWzMV/BDvWBtFtoXZeomlGh89sUbAvmq/DafIgvLACw5X8=
  file: build/distributions/xmlcalabash1-gradle-$TRAVIS_TAG.zip
  on:
    all_branches: true
    tags: true
