language: java
script: gradle dist -x test
sudo: false
install:
- echo sonatypeUsername=none >> gradle.properties
- echo sonatypePassword=none >> gradle.properties

deploy:
  provider: releases
  file:
    - build/distributions/xmlcalabash1-gradle-$TRAVIS_TAG.zip
  on:
    all_branches: true
    tags: true

